export default [
  {name: 'coconut', source: require('@assets/images/rst-images/coconut.png')},
  {name: 'mango', source: require('@assets/images/rst-images/mango.png')},
  {
    name: 'blueberries',
    source: require('@assets/images/rst-images/blueberries.png'),
  },
  {name: 'cheese', source: require('@assets/images/rst-images/cheese.png')},
  {name: 'chestnut', source: require('@assets/images/rst-images/chestnut.png')},
  {name: 'broccoli', source: require('@assets/images/rst-images/broccoli.png')},
  {
    name: 'green-apple',
    source: require('@assets/images/rst-images/green-apple.png'),
  },
  {name: 'eggplant', source: require('@assets/images/rst-images/eggplant.png')},
  {name: 'olive', source: require('@assets/images/rst-images/olive.png')},
  {name: 'peach', source: require('@assets/images/rst-images/peach.png')},
  {
    name: 'pineapple',
    source: require('@assets/images/rst-images/pineapple.png'),
  },
  {
    name: 'poultry-leg',
    source: require('@assets/images/rst-images/poultry-leg.png'),
  },
  {name: 'garlic', source: require('@assets/images/rst-images/garlic.png')},
  {name: 'kiwi', source: require('@assets/images/rst-images/kiwi.png')},
  {
    name: 'leafy-green',
    source: require('@assets/images/rst-images/leafy-green.png'),
  },
  {
    name: 'chocolate',
    source: require('@assets/images/rst-images/chocolate.png'),
  },
  {
    name: 'hamburger',
    source: require('@assets/images/rst-images/hamburger.png'),
  },
  {
    name: 'ice-cream',
    source: require('@assets/images/rst-images/ice-cream.png'),
  },
  {name: 'bread', source: require('@assets/images/rst-images/bread.png')},
  {name: 'cherries', source: require('@assets/images/rst-images/cherries.png')},
  {name: 'sushi', source: require('@assets/images/rst-images/sushi.png')},
  {name: 'potato', source: require('@assets/images/rst-images/potato.png')},
  {name: 'pancakes', source: require('@assets/images/rst-images/pancakes.png')},
  {name: 'cucumber', source: require('@assets/images/rst-images/cucumber.png')},
  {name: 'salad', source: require('@assets/images/rst-images/salad.png')},
  {name: 'corn', source: require('@assets/images/rst-images/corn.png')},
  {name: 'popcorn', source: require('@assets/images/rst-images/popcorn.png')},
  {name: 'mushroom', source: require('@assets/images/rst-images/mushroom.png')},
  {name: 'doughnut', source: require('@assets/images/rst-images/doughnut.png')},
  {name: 'pear', source: require('@assets/images/rst-images/pear.png')},
  {
    name: 'bell-pepper',
    source: require('@assets/images/rst-images/bell-pepper.png'),
  },
  {
    name: 'watermelon',
    source: require('@assets/images/rst-images/watermelon.png'),
  },
  {name: 'grapes', source: require('@assets/images/rst-images/grapes.png')},
  {name: 'banana', source: require('@assets/images/rst-images/banana.png')},
  {name: 'hot-dog', source: require('@assets/images/rst-images/hot-dog.png')},
  {name: 'lemon', source: require('@assets/images/rst-images/lemon.png')},
  {name: 'ginger', source: require('@assets/images/rst-images/ginger.png')},
  {
    name: 'strawberry',
    source: require('@assets/images/rst-images/strawberry.png'),
  },
  {name: 'beans', source: require('@assets/images/rst-images/beans.png')},
  {name: 'pizza', source: require('@assets/images/rst-images/pizza.png')},
  {name: 'pea', source: require('@assets/images/rst-images/pea.png')},
  {
    name: 'red-apple',
    source: require('@assets/images/rst-images/red-apple.png'),
  },
  {
    name: 'hot-pepper',
    source: require('@assets/images/rst-images/hot-pepper.png'),
  },
  {name: 'waffle', source: require('@assets/images/rst-images/waffle.png')},
  {name: 'egg', source: require('@assets/images/rst-images/egg.png')},
  {
    name: 'tangerine',
    source: require('@assets/images/rst-images/tangerine.png'),
  },
  {name: 'tomato', source: require('@assets/images/rst-images/tomato.png')},
  {name: 'onion', source: require('@assets/images/rst-images/onion.png')},
  {
    name: 'rice-ball',
    source: require('@assets/images/rst-images/rice-ball.png'),
  },
  {name: 'cookie', source: require('@assets/images/rst-images/cookie.png')},
  {
    name: 'french-fries',
    source: require('@assets/images/rst-images/french-fries.png'),
  },
  {name: 'melon', source: require('@assets/images/rst-images/melon.png')},
  {name: 'avocado', source: require('@assets/images/rst-images/avocado.png')},
  {name: 'carrot', source: require('@assets/images/rst-images/carrot.png')},
  {name: 'peanuts', source: require('@assets/images/rst-images/peanuts.png')},
  {name: 'yam', source: require('@assets/images/rst-images/yam.png')},
];
