export const LOGIN = 'auth/LOGIN'
export const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS'
export const LOGIN_ERROR = 'auth/LOGIN_ERROR'

export const SIGN_OUT = 'auth/SIGN_OUT'
export const RESET_PROFILE = 'auth/RESET_PROFILE'
export const SET_TOKEN = 'auth/SET_TOKEN'
export const GET_TOKEN = 'auth/GET_TOKEN'
export const GET_DB_TOKEN = 'auth/GET_DB_TOKEN'
export const GET_DB_DATA = 'auth/GET_DB_DATA'
export const CLEAR_ERRORS = 'auth/CLEAR_ERRORS'
export const RESET_AUTH = 'auth/RESET_AUTH'
