export default [
  {source: require('@assets/images/mem-images/parrot.png'), name: 'parrot'},
  {source: require('@assets/images/mem-images/duck.png'), name: 'duck'},
  {source: require('@assets/images/mem-images/dog.png'), name: 'dog'},
  {
    source: require('@assets/images/mem-images/manualwheelchair.png'),
    name: 'manualwheelchair',
  },
  {
    source: require('@assets/images/mem-images/volleyball.png'),
    name: 'volleyball',
  },
  {source: require('@assets/images/mem-images/gaspump.png'), name: 'gaspump'},
  {source: require('@assets/images/mem-images/gear.png'), name: 'gear'},
  {source: require('@assets/images/mem-images/desert.png'), name: 'desert'},
  {source: require('@assets/images/mem-images/fan.png'), name: 'fan'},
  {source: require('@assets/images/mem-images/horse.png'), name: 'horse'},
  {source: require('@assets/images/mem-images/mushroom.png'), name: 'mushroom'},
  {source: require('@assets/images/mem-images/dodo.png'), name: 'dodo'},
  {source: require('@assets/images/mem-images/king.png'), name: 'king'},
  {source: require('@assets/images/mem-images/manshoe.png'), name: 'manshoe'},
  {source: require('@assets/images/mem-images/womanhat.png'), name: 'womanhat'},
  {
    source: require('@assets/images/mem-images/dollarbill.png'),
    name: 'dollarbill',
  },
  {source: require('@assets/images/mem-images/rabbit.png'), name: 'rabbit'},
  {source: require('@assets/images/mem-images/bowling.png'), name: 'bowling'},
  {
    source: require('@assets/images/mem-images/sunflower.png'),
    name: 'sunflower',
  },
  {
    source: require('@assets/images/mem-images/nightcity.png'),
    name: 'nightcity',
  },
  {source: require('@assets/images/mem-images/hairpick.png'), name: 'hairpick'},
  {source: require('@assets/images/mem-images/hospital.png'), name: 'hospital'},
  {source: require('@assets/images/mem-images/whale.png'), name: 'whale'},
  {
    source: require('@assets/images/mem-images/boomerang.png'),
    name: 'boomerang',
  },
  {
    source: require('@assets/images/mem-images/musicalnote.png'),
    name: 'musicalnote',
  },
  {source: require('@assets/images/mem-images/hibiscus.png'), name: 'hibiscus'},
  {source: require('@assets/images/mem-images/trophy.png'), name: 'trophy'},
  {source: require('@assets/images/mem-images/unicorn.png'), name: 'unicorn'},
  {source: require('@assets/images/mem-images/plunger.png'), name: 'plunger'},
  {
    source: require('@assets/images/mem-images/snowflake.png'),
    name: 'snowflake',
  },
  {
    source: require('@assets/images/mem-images/newspaper.png'),
    name: 'newspaper',
  },
  {source: require('@assets/images/mem-images/stop.png'), name: 'stop'},
  {source: require('@assets/images/mem-images/poopface.png'), name: 'poopface'},
  {
    source: require('@assets/images/mem-images/togetherhands.png'),
    name: 'togetherhands',
  },
  {
    source: require('@assets/images/mem-images/womanwheelchair.png'),
    name: 'womanwheelchair',
  },
  {source: require('@assets/images/mem-images/turtle.png'), name: 'turtle'},
  {source: require('@assets/images/mem-images/ruler.png'), name: 'ruler'},
  {
    source: require('@assets/images/mem-images/rhinoceros.png'),
    name: 'rhinoceros',
  },
  {
    source: require('@assets/images/mem-images/astronaut.png'),
    name: 'astronaut',
  },
  {
    source: require('@assets/images/mem-images/studiomicrophone.png'),
    name: 'studiomicrophone',
  },
  {
    source: require('@assets/images/mem-images/magnifyingglass.png'),
    name: 'magnifyingglass',
  },
  {source: require('@assets/images/mem-images/disguise.png'), name: 'disguise'},
  {
    source: require('@assets/images/mem-images/flagcanada.png'),
    name: 'flagcanada',
  },
  {source: require('@assets/images/mem-images/plant.png'), name: 'plant'},
  {source: require('@assets/images/mem-images/xwoman.png'), name: 'xwoman'},
  {source: require('@assets/images/mem-images/battery.png'), name: 'battery'},
  {source: require('@assets/images/mem-images/beaver.png'), name: 'beaver'},
  {
    source: require('@assets/images/mem-images/transgenderflag.png'),
    name: 'transgenderflag',
  },
  {
    source: require('@assets/images/mem-images/satelliteantenna.png'),
    name: 'satelliteantenna',
  },
  {
    source: require('@assets/images/mem-images/constructioncrane.png'),
    name: 'constructioncrane',
  },
  {
    source: require('@assets/images/mem-images/rescuehelmet.png'),
    name: 'rescuehelmet',
  },
  {
    source: require('@assets/images/mem-images/trackball.png'),
    name: 'trackball',
  },
  {source: require('@assets/images/mem-images/teacher.png'), name: 'teacher'},
  {source: require('@assets/images/mem-images/spider.png'), name: 'spider'},
  {source: require('@assets/images/mem-images/train.png'), name: 'train'},
  {source: require('@assets/images/mem-images/goal.png'), name: 'goal'},
  {source: require('@assets/images/mem-images/plug.png'), name: 'plug'},
  {source: require('@assets/images/mem-images/bluefish.png'), name: 'bluefish'},
  {source: require('@assets/images/mem-images/skull.png'), name: 'skull'},
  {source: require('@assets/images/mem-images/maracas.png'), name: 'maracas'},
  {
    source: require('@assets/images/mem-images/controller.png'),
    name: 'controller',
  },
  {source: require('@assets/images/mem-images/bell.png'), name: 'bell'},
  {source: require('@assets/images/mem-images/coolface.png'), name: 'coolface'},
  {
    source: require('@assets/images/mem-images/wastebasket.png'),
    name: 'wastebasket',
  },
  {
    source: require('@assets/images/mem-images/satellite.png'),
    name: 'satellite',
  },
  {source: require('@assets/images/mem-images/mouth.png'), name: 'mouth'},
  {source: require('@assets/images/mem-images/dolphine.png'), name: 'dolphine'},
  {
    source: require('@assets/images/mem-images/tokyotower.png'),
    name: 'tokyotower',
  },
  {source: require('@assets/images/mem-images/taxi.png'), name: 'taxi'},
  {source: require('@assets/images/mem-images/radio.png'), name: 'radio'},
  {source: require('@assets/images/mem-images/dna.png'), name: 'dna'},
  {
    source: require('@assets/images/mem-images/whiteflag.png'),
    name: 'whiteflag',
  },
  {
    source: require('@assets/images/mem-images/lesbianfamily.png'),
    name: 'lesbianfamily',
  },
  {source: require('@assets/images/mem-images/castle.png'), name: 'castle'},
  {
    source: require('@assets/images/mem-images/lifesaver.png'),
    name: 'lifesaver',
  },
  {source: require('@assets/images/mem-images/shield.png'), name: 'shield'},
  {source: require('@assets/images/mem-images/bicep.png'), name: 'bicep'},
  {source: require('@assets/images/mem-images/envelope.png'), name: 'envelope'},
  {source: require('@assets/images/mem-images/seat.png'), name: 'seat'},
  {source: require('@assets/images/mem-images/school.png'), name: 'school'},
  {source: require('@assets/images/mem-images/magnet.png'), name: 'magnet'},
  {
    source: require('@assets/images/mem-images/womansandal.png'),
    name: 'womansandal',
  },
  {source: require('@assets/images/mem-images/rose.png'), name: 'rose'},
  {source: require('@assets/images/mem-images/iceskate.png'), name: 'iceskate'},
  {
    source: require('@assets/images/mem-images/ambulance.png'),
    name: 'ambulance',
  },
  {source: require('@assets/images/mem-images/fly.png'), name: 'fly'},
  {source: require('@assets/images/mem-images/worm.png'), name: 'worm'},
  {
    source: require('@assets/images/mem-images/graduationcap.png'),
    name: 'graduationcap',
  },
  {source: require('@assets/images/mem-images/bathtub.png'), name: 'bathtub'},
  {source: require('@assets/images/mem-images/ship.png'), name: 'ship'},
  {
    source: require('@assets/images/mem-images/telescope.png'),
    name: 'telescope',
  },
  {source: require('@assets/images/mem-images/clover.png'), name: 'clover'},
  {source: require('@assets/images/mem-images/flipflop.png'), name: 'flipflop'},
  {source: require('@assets/images/mem-images/key.png'), name: 'key'},
  {source: require('@assets/images/mem-images/elephant.png'), name: 'elephant'},
  {
    source: require('@assets/images/mem-images/angryface.png'),
    name: 'angryface',
  },
  {source: require('@assets/images/mem-images/package.png'), name: 'package'},
  {source: require('@assets/images/mem-images/fire.png'), name: 'fire'},
  {source: require('@assets/images/mem-images/lion.png'), name: 'lion'},
  {
    source: require('@assets/images/mem-images/computermouse.png'),
    name: 'computermouse',
  },
  {
    source: require('@assets/images/mem-images/statueofliberty.png'),
    name: 'statueofliberty',
  },
  {source: require('@assets/images/mem-images/shell.png'), name: 'shell'},
  {
    source: require('@assets/images/mem-images/fireextinguisher.png'),
    name: 'fireextinguisher',
  },
  {
    source: require('@assets/images/mem-images/videocassette.png'),
    name: 'videocassette',
  },
  {source: require('@assets/images/mem-images/fishflag.png'), name: 'fishflag'},
  {
    source: require('@assets/images/mem-images/parachute.png'),
    name: 'parachute',
  },
  {source: require('@assets/images/mem-images/keyboard.png'), name: 'keyboard'},
  {source: require('@assets/images/mem-images/monorail.png'), name: 'monorail'},
  {source: require('@assets/images/mem-images/flute.png'), name: 'flute'},
  {source: require('@assets/images/mem-images/wheat.png'), name: 'wheat'},
  {source: require('@assets/images/mem-images/camel.png'), name: 'camel'},
  {
    source: require('@assets/images/mem-images/traingularflag.png'),
    name: 'traingularflag',
  },
  {source: require('@assets/images/mem-images/wheel.png'), name: 'wheel'},
  {
    source: require('@assets/images/mem-images/locomotive.png'),
    name: 'locomotive',
  },
  {
    source: require('@assets/images/mem-images/postoffice.png'),
    name: 'postoffice',
  },
  {source: require('@assets/images/mem-images/spade.png'), name: 'spade'},
  {source: require('@assets/images/mem-images/eagle.png'), name: 'eagle'},
  {source: require('@assets/images/mem-images/swan.png'), name: 'swan'},
  {
    source: require('@assets/images/mem-images/mutedspeaker.png'),
    name: 'mutedspeaker',
  },
  {source: require('@assets/images/mem-images/turkey.png'), name: 'turkey'},
  {source: require('@assets/images/mem-images/chess.png'), name: 'chess'},
  {
    source: require('@assets/images/mem-images/helicopter.png'),
    name: 'helicopter',
  },
  {source: require('@assets/images/mem-images/wizard.png'), name: 'wizard'},
  {
    source: require('@assets/images/mem-images/articulatedlorry.png'),
    name: 'articulatedlorry',
  },
  {source: require('@assets/images/mem-images/cricket.png'), name: 'cricket'},
  {source: require('@assets/images/mem-images/flamingo.png'), name: 'flamingo'},
  {source: require('@assets/images/mem-images/labcoat.png'), name: 'labcoat'},
  {source: require('@assets/images/mem-images/golfhole.png'), name: 'golfhole'},
  {source: require('@assets/images/mem-images/files.png'), name: 'files'},
  {
    source: require('@assets/images/mem-images/recyclingsymbol.png'),
    name: 'recyclingsymbol',
  },
  {source: require('@assets/images/mem-images/chef.png'), name: 'chef'},
  {source: require('@assets/images/mem-images/brain.png'), name: 'brain'},
  {
    source: require('@assets/images/mem-images/toothbrush.png'),
    name: 'toothbrush',
  },
  {source: require('@assets/images/mem-images/nose.png'), name: 'nose'},
  {source: require('@assets/images/mem-images/puzzle.png'), name: 'puzzle'},
  {source: require('@assets/images/mem-images/octopus.png'), name: 'octopus'},
  {source: require('@assets/images/mem-images/hyacinth.png'), name: 'hyacinth'},
  {source: require('@assets/images/mem-images/squid.png'), name: 'squid'},
  {
    source: require('@assets/images/mem-images/runningshoe.png'),
    name: 'runningshoe',
  },
  {source: require('@assets/images/mem-images/books.png'), name: 'books'},
  {source: require('@assets/images/mem-images/zebra.png'), name: 'zebra'},
  {
    source: require('@assets/images/mem-images/microphone.png'),
    name: 'microphone',
  },
  {source: require('@assets/images/mem-images/fistbump.png'), name: 'fistbump'},
  {
    source: require('@assets/images/mem-images/briefcase.png'),
    name: 'briefcase',
  },
  {source: require('@assets/images/mem-images/tiger.png'), name: 'tiger'},
  {source: require('@assets/images/mem-images/watergun.png'), name: 'watergun'},
  {source: require('@assets/images/mem-images/kangaroo.png'), name: 'kangaroo'},
  {
    source: require('@assets/images/mem-images/fountainpen.png'),
    name: 'fountainpen',
  },
  {source: require('@assets/images/mem-images/surfer.png'), name: 'surfer'},
  {source: require('@assets/images/mem-images/dragon.png'), name: 'dragon'},
  {
    source: require('@assets/images/mem-images/filecabinet.png'),
    name: 'filecabinet',
  },
  {
    source: require('@assets/images/mem-images/toiletpaper.png'),
    name: 'toiletpaper',
  },
  {
    source: require('@assets/images/mem-images/rainbowflag.png'),
    name: 'rainbowflag',
  },
  {source: require('@assets/images/mem-images/sheep.png'), name: 'sheep'},
  {source: require('@assets/images/mem-images/candle.png'), name: 'candle'},
  {source: require('@assets/images/mem-images/cactus.png'), name: 'cactus'},
  {source: require('@assets/images/mem-images/multiply.png'), name: 'multiply'},
  {source: require('@assets/images/mem-images/camping.png'), name: 'camping'},
  {source: require('@assets/images/mem-images/lacrosse.png'), name: 'lacrosse'},
  {source: require('@assets/images/mem-images/ticket.png'), name: 'ticket'},
  {
    source: require('@assets/images/mem-images/adhesivebandage.png'),
    name: 'adhesivebandage',
  },
  {source: require('@assets/images/mem-images/boquet.png'), name: 'boquet'},
  {source: require('@assets/images/mem-images/backpack.png'), name: 'backpack'},
  {
    source: require('@assets/images/mem-images/redlantern.png'),
    name: 'redlantern',
  },
  {
    source: require('@assets/images/mem-images/badminton.png'),
    name: 'badminton',
  },
  {
    source: require('@assets/images/mem-images/television.png'),
    name: 'television',
  },
  {source: require('@assets/images/mem-images/handbag.png'), name: 'handbag'},
  {
    source: require('@assets/images/mem-images/automobile.png'),
    name: 'automobile',
  },
  {source: require('@assets/images/mem-images/doctor.png'), name: 'doctor'},
  {source: require('@assets/images/mem-images/shark.png'), name: 'shark'},
  {
    source: require('@assets/images/mem-images/mapleleaf.png'),
    name: 'mapleleaf',
  },
  {source: require('@assets/images/mem-images/party.png'), name: 'party'},
  {source: require('@assets/images/mem-images/fairy.png'), name: 'fairy'},
  {source: require('@assets/images/mem-images/cow.png'), name: 'cow'},
  {source: require('@assets/images/mem-images/crayon.png'), name: 'crayon'},
  {source: require('@assets/images/mem-images/panda.png'), name: 'panda'},
  {source: require('@assets/images/mem-images/blackcat.png'), name: 'blackcat'},
  {source: require('@assets/images/mem-images/scarf.png'), name: 'scarf'},
  {source: require('@assets/images/mem-images/umbrella.png'), name: 'umbrella'},
  {
    source: require('@assets/images/mem-images/butterfly.png'),
    name: 'butterfly',
  },
  {source: require('@assets/images/mem-images/hedghog.png'), name: 'hedghog'},
  {source: require('@assets/images/mem-images/testtube.png'), name: 'testtube'},
  {source: require('@assets/images/mem-images/rock.png'), name: 'rock'},
  {
    source: require('@assets/images/mem-images/policecar.png'),
    name: 'policecar',
  },
  {source: require('@assets/images/mem-images/toolbox.png'), name: 'toolbox'},
  {source: require('@assets/images/mem-images/sunrise.png'), name: 'sunrise'},
  {source: require('@assets/images/mem-images/volcano.png'), name: 'volcano'},
  {source: require('@assets/images/mem-images/lipstick.png'), name: 'lipstick'},
  {
    source: require('@assets/images/mem-images/heterofamily.png'),
    name: 'heterofamily',
  },
  {
    source: require('@assets/images/mem-images/vertical_traffic_light.png'),
    name: 'vertical_traffic_light',
  },
  {
    source: require('@assets/images/mem-images/shoppingcart.png'),
    name: 'shoppingcart',
  },
  {source: require('@assets/images/mem-images/luggage.png'), name: 'luggage'},
  {
    source: require('@assets/images/mem-images/speechballoon.png'),
    name: 'speechballoon',
  },
  {
    source: require('@assets/images/mem-images/leftpoint.png'),
    name: 'leftpoint',
  },
  {source: require('@assets/images/mem-images/ant.png'), name: 'ant'},
  {source: require('@assets/images/mem-images/fountain.png'), name: 'fountain'},
  {
    source: require('@assets/images/mem-images/chequeredflag.png'),
    name: 'chequeredflag',
  },
  {
    source: require('@assets/images/mem-images/hourglass.png'),
    name: 'hourglass',
  },
  {
    source: require('@assets/images/mem-images/musicalscore.png'),
    name: 'musicalscore',
  },
  {source: require('@assets/images/mem-images/scissors.png'), name: 'scissors'},
  {source: require('@assets/images/mem-images/circus.png'), name: 'circus'},
  {source: require('@assets/images/mem-images/oman.png'), name: 'oman'},
  {
    source: require('@assets/images/mem-images/dancingman.png'),
    name: 'dancingman',
  },
  {source: require('@assets/images/mem-images/stadium.png'), name: 'stadium'},
  {source: require('@assets/images/mem-images/owl.png'), name: 'owl'},
  {source: require('@assets/images/mem-images/present.png'), name: 'present'},
  {
    source: require('@assets/images/mem-images/loveyouhand.png'),
    name: 'loveyouhand',
  },
  {
    source: require('@assets/images/mem-images/floppydisk.png'),
    name: 'floppydisk',
  },
  {
    source: require('@assets/images/mem-images/wheelchairsymbol.png'),
    name: 'wheelchairsymbol',
  },
  {source: require('@assets/images/mem-images/house.png'), name: 'house'},
  {source: require('@assets/images/mem-images/tennis.png'), name: 'tennis'},
  {source: require('@assets/images/mem-images/ladybug.png'), name: 'ladybug'},
  {source: require('@assets/images/mem-images/jeans.png'), name: 'jeans'},
  {source: require('@assets/images/mem-images/moai.png'), name: 'moai'},
  {
    source: require('@assets/images/mem-images/bowandarrow.png'),
    name: 'bowandarrow',
  },
  {
    source: require('@assets/images/mem-images/clapperboard.png'),
    name: 'clapperboard',
  },
  {source: require('@assets/images/mem-images/knot.png'), name: 'knot'},
  {
    source: require('@assets/images/mem-images/barberpole.png'),
    name: 'barberpole',
  },
  {source: require('@assets/images/mem-images/frisbee.png'), name: 'frisbee'},
  {source: require('@assets/images/mem-images/pilot.png'), name: 'pilot'},
  {source: require('@assets/images/mem-images/bed.png'), name: 'bed'},
  {source: require('@assets/images/mem-images/bee.png'), name: 'bee'},
  {source: require('@assets/images/mem-images/trex.png'), name: 'trex'},
  {source: require('@assets/images/mem-images/abacus.png'), name: 'abacus'},
  {source: require('@assets/images/mem-images/ghost.png'), name: 'ghost'},
  {source: require('@assets/images/mem-images/oldkey.png'), name: 'oldkey'},
  {
    source: require('@assets/images/mem-images/flashlight.png'),
    name: 'flashlight',
  },
  {source: require('@assets/images/mem-images/peacock.png'), name: 'peacock'},
  {source: require('@assets/images/mem-images/earth.png'), name: 'earth'},
  {
    source: require('@assets/images/mem-images/speakervolume.png'),
    name: 'speakervolume',
  },
  {source: require('@assets/images/mem-images/bride.png'), name: 'bride'},
  {source: require('@assets/images/mem-images/soccer.png'), name: 'soccer'},
  {
    source: require('@assets/images/mem-images/lightning.png'),
    name: 'lightning',
  },
  {
    source: require('@assets/images/mem-images/flyingsaucer.png'),
    name: 'flyingsaucer',
  },
  {source: require('@assets/images/mem-images/ladder.png'), name: 'ladder'},
  {source: require('@assets/images/mem-images/socks.png'), name: 'socks'},
  {source: require('@assets/images/mem-images/genie.png'), name: 'genie'},
  {source: require('@assets/images/mem-images/painting.png'), name: 'painting'},
  {source: require('@assets/images/mem-images/onedad.png'), name: 'onedad'},
  {source: require('@assets/images/mem-images/blood.png'), name: 'blood'},
  {source: require('@assets/images/mem-images/violin.png'), name: 'violin'},
  {source: require('@assets/images/mem-images/chains.png'), name: 'chains'},
  {source: require('@assets/images/mem-images/notebook.png'), name: 'notebook'},
  {source: require('@assets/images/mem-images/wolf.png'), name: 'wolf'},
  {source: require('@assets/images/mem-images/facepalm.png'), name: 'facepalm'},
  {source: require('@assets/images/mem-images/ribbon.png'), name: 'ribbon'},
  {source: require('@assets/images/mem-images/foggy.png'), name: 'foggy'},
  {source: require('@assets/images/mem-images/redhair.png'), name: 'redhair'},
  {source: require('@assets/images/mem-images/joker.png'), name: 'joker'},
  {
    source: require('@assets/images/mem-images/dancingwoman.png'),
    name: 'dancingwoman',
  },
  {source: require('@assets/images/mem-images/hamster.png'), name: 'hamster'},
  {source: require('@assets/images/mem-images/film.png'), name: 'film'},
  {source: require('@assets/images/mem-images/moon.png'), name: 'moon'},
  {
    source: require('@assets/images/mem-images/musicalnotes.png'),
    name: 'musicalnotes',
  },
  {source: require('@assets/images/mem-images/blouse.png'), name: 'blouse'},
  {
    source: require('@assets/images/mem-images/mousetrap.png'),
    name: 'mousetrap',
  },
  {
    source: require('@assets/images/mem-images/thermostat.png'),
    name: 'thermostat',
  },
  {source: require('@assets/images/mem-images/basket.png'), name: 'basket'},
  {source: require('@assets/images/mem-images/penguin.png'), name: 'penguin'},
  {source: require('@assets/images/mem-images/aritist.png'), name: 'aritist'},
  {source: require('@assets/images/mem-images/alarm.png'), name: 'alarm'},
  {
    source: require('@assets/images/mem-images/baskteballplayer.png'),
    name: 'baskteballplayer',
  },
  {
    source: require('@assets/images/mem-images/scaredface.png'),
    name: 'scaredface',
  },
  {source: require('@assets/images/mem-images/canoe.png'), name: 'canoe'},
  {
    source: require('@assets/images/mem-images/closedmailbox.png'),
    name: 'closedmailbox',
  },
  {
    source: require('@assets/images/mem-images/screwdriver.png'),
    name: 'screwdriver',
  },
  {source: require('@assets/images/mem-images/coldface.png'), name: 'coldface'},
  {source: require('@assets/images/mem-images/mirror.png'), name: 'mirror'},
  {source: require('@assets/images/mem-images/hockey.png'), name: 'hockey'},
  {
    source: require('@assets/images/mem-images/couchandlamp.png'),
    name: 'couchandlamp',
  },
  {
    source: require('@assets/images/mem-images/scientist.png'),
    name: 'scientist',
  },
  {source: require('@assets/images/mem-images/marmaid.png'), name: 'marmaid'},
  {
    source: require('@assets/images/mem-images/balancescale.png'),
    name: 'balancescale',
  },
  {source: require('@assets/images/mem-images/ring.png'), name: 'ring'},
  {source: require('@assets/images/mem-images/pushpin.png'), name: 'pushpin'},
  {source: require('@assets/images/mem-images/diyalamp.png'), name: 'diyalamp'},
  {source: require('@assets/images/mem-images/sloth.png'), name: 'sloth'},
  {source: require('@assets/images/mem-images/airplane.png'), name: 'airplane'},
  {source: require('@assets/images/mem-images/coat.png'), name: 'coat'},
  {
    source: require('@assets/images/mem-images/moviecamera.png'),
    name: 'moviecamera',
  },
  {source: require('@assets/images/mem-images/racoon.png'), name: 'racoon'},
  {
    source: require('@assets/images/mem-images/closedbook.png'),
    name: 'closedbook',
  },
  {
    source: require('@assets/images/mem-images/fleurdelis.png'),
    name: 'fleurdelis',
  },
  {
    source: require('@assets/images/mem-images/rollerskate.png'),
    name: 'rollerskate',
  },
  {source: require('@assets/images/mem-images/disco.png'), name: 'disco'},
  {source: require('@assets/images/mem-images/bookmark.png'), name: 'bookmark'},
  {source: require('@assets/images/mem-images/balloon.png'), name: 'balloon'},
  {source: require('@assets/images/mem-images/santa.png'), name: 'santa'},
  {source: require('@assets/images/mem-images/boxing.png'), name: 'boxing'},
  {
    source: require('@assets/images/mem-images/accordian.png'),
    name: 'accordian',
  },
  {
    source: require('@assets/images/mem-images/controlknobs.png'),
    name: 'controlknobs',
  },
  {source: require('@assets/images/mem-images/palmtree.png'), name: 'palmtree'},
  {source: require('@assets/images/mem-images/rocket.png'), name: 'rocket'},
  {source: require('@assets/images/mem-images/chair.png'), name: 'chair'},
  {source: require('@assets/images/mem-images/wave.png'), name: 'wave'},
  {source: require('@assets/images/mem-images/gemstone.png'), name: 'gemstone'},
  {source: require('@assets/images/mem-images/dice.png'), name: 'dice'},
  {source: require('@assets/images/mem-images/oldphone.png'), name: 'oldphone'},
  {source: require('@assets/images/mem-images/graduate.png'), name: 'graduate'},
  {
    source: require('@assets/images/mem-images/rollercoaster.png'),
    name: 'rollercoaster',
  },
  {source: require('@assets/images/mem-images/window.png'), name: 'window'},
  {source: require('@assets/images/mem-images/oildrum.png'), name: 'oildrum'},
  {source: require('@assets/images/mem-images/alien.png'), name: 'alien'},
  {source: require('@assets/images/mem-images/sari.png'), name: 'sari'},
  {
    source: require('@assets/images/mem-images/ballotbox.png'),
    name: 'ballotbox',
  },
  {
    source: require('@assets/images/mem-images/motorcycle.png'),
    name: 'motorcycle',
  },
  {source: require('@assets/images/mem-images/tooth.png'), name: 'tooth'},
  {
    source: require('@assets/images/mem-images/firetruck.png'),
    name: 'firetruck',
  },
  {source: require('@assets/images/mem-images/raishand.png'), name: 'raishand'},
  {source: require('@assets/images/mem-images/mountain.png'), name: 'mountain'},
  {
    source: require('@assets/images/mem-images/medicalsymbol.png'),
    name: 'medicalsymbol',
  },
  {source: require('@assets/images/mem-images/cloud.png'), name: 'cloud'},
  {source: require('@assets/images/mem-images/moneybag.png'), name: 'moneybag'},
  {source: require('@assets/images/mem-images/shorts.png'), name: 'shorts'},
  {
    source: require('@assets/images/mem-images/paintbrush.png'),
    name: 'paintbrush',
  },
  {
    source: require('@assets/images/mem-images/pirateflag.png'),
    name: 'pirateflag',
  },
  {
    source: require('@assets/images/mem-images/electricscooter.png'),
    name: 'electricscooter',
  },
  {
    source: require('@assets/images/mem-images/crossswords.png'),
    name: 'crossswords',
  },
  {
    source: require('@assets/images/mem-images/carouselhorse.png'),
    name: 'carouselhorse',
  },
  {source: require('@assets/images/mem-images/water.png'), name: 'water'},
  {
    source: require('@assets/images/mem-images/pufferfish.png'),
    name: 'pufferfish',
  },
  {
    source: require('@assets/images/mem-images/moneyenvelope.png'),
    name: 'moneyenvelope',
  },
  {source: require('@assets/images/mem-images/tree.png'), name: 'tree'},
  {source: require('@assets/images/mem-images/barfface.png'), name: 'barfface'},
  {source: require('@assets/images/mem-images/robot.png'), name: 'robot'},
  {source: require('@assets/images/mem-images/calendar.png'), name: 'calendar'},
  {source: require('@assets/images/mem-images/medal.png'), name: 'medal'},
  {
    source: require('@assets/images/mem-images/cryingface.png'),
    name: 'cryingface',
  },
  {source: require('@assets/images/mem-images/door.png'), name: 'door'},
  {source: require('@assets/images/mem-images/drum.png'), name: 'drum'},
  {
    source: require('@assets/images/mem-images/microscope.png'),
    name: 'microscope',
  },
  {source: require('@assets/images/mem-images/zombie.png'), name: 'zombie'},
  {
    source: require('@assets/images/mem-images/video_camera.png'),
    name: 'video_camera',
  },
  {
    source: require('@assets/images/mem-images/taekwondo.png'),
    name: 'taekwondo',
  },
  {source: require('@assets/images/mem-images/heelshoe.png'), name: 'heelshoe'},
  {
    source: require('@assets/images/mem-images/trolley_bus.png'),
    name: 'trolley_bus',
  },
  {source: require('@assets/images/mem-images/cap.png'), name: 'cap'},
  {
    source: require('@assets/images/mem-images/sewingneedle.png'),
    name: 'sewingneedle',
  },
  {
    source: require('@assets/images/mem-images/firefighter.png'),
    name: 'firefighter',
  },
  {source: require('@assets/images/mem-images/car.png'), name: 'car'},
  {source: require('@assets/images/mem-images/nest.png'), name: 'nest'},
  {source: require('@assets/images/mem-images/wand.png'), name: 'wand'},
  {source: require('@assets/images/mem-images/axe.png'), name: 'axe'},
  {source: require('@assets/images/mem-images/zzz.png'), name: 'zzz'},
  {source: require('@assets/images/mem-images/tulip.png'), name: 'tulip'},
  {source: require('@assets/images/mem-images/baseball.png'), name: 'baseball'},
  {source: require('@assets/images/mem-images/chipmunk.png'), name: 'chipmunk'},
  {
    source: require('@assets/images/mem-images/headphone.png'),
    name: 'headphone',
  },
  {
    source: require('@assets/images/mem-images/yellowfish.png'),
    name: 'yellowfish',
  },
  {source: require('@assets/images/mem-images/eye.png'), name: 'eye'},
  {source: require('@assets/images/mem-images/pill.png'), name: 'pill'},
  {source: require('@assets/images/mem-images/pingpong.png'), name: 'pingpong'},
  {
    source: require('@assets/images/mem-images/radioactivesymbol.png'),
    name: 'radioactivesymbol',
  },
  {source: require('@assets/images/mem-images/lotus.png'), name: 'lotus'},
  {source: require('@assets/images/mem-images/dove.png'), name: 'dove'},
  {source: require('@assets/images/mem-images/rooster.png'), name: 'rooster'},
  {
    source: require('@assets/images/mem-images/autorickshaw.png'),
    name: 'autorickshaw',
  },
  {source: require('@assets/images/mem-images/phone.png'), name: 'phone'},
  {source: require('@assets/images/mem-images/football.png'), name: 'football'},
  {
    source: require('@assets/images/mem-images/jellyfish.png'),
    name: 'jellyfish',
  },
  {source: require('@assets/images/mem-images/tractor.png'), name: 'tractor'},
  {source: require('@assets/images/mem-images/bluebird.png'), name: 'bluebird'},
  {source: require('@assets/images/mem-images/lungs.png'), name: 'lungs'},
  {
    source: require('@assets/images/mem-images/safetyvest.png'),
    name: 'safetyvest',
  },
  {
    source: require('@assets/images/mem-images/superhero.png'),
    name: 'superhero',
  },
  {source: require('@assets/images/mem-images/foot.png'), name: 'foot'},
  {
    source: require('@assets/images/mem-images/footprints.png'),
    name: 'footprints',
  },
  {source: require('@assets/images/mem-images/diamond.png'), name: 'diamond'},
  {
    source: require('@assets/images/mem-images/basketball.png'),
    name: 'basketball',
  },
  {source: require('@assets/images/mem-images/crab.png'), name: 'crab'},
  {source: require('@assets/images/mem-images/snowman.png'), name: 'snowman'},
  {source: require('@assets/images/mem-images/monkey.png'), name: 'monkey'},
  {source: require('@assets/images/mem-images/judge.png'), name: 'judge'},
  {source: require('@assets/images/mem-images/oldman.png'), name: 'oldman'},
  {
    source: require('@assets/images/mem-images/inputlatinuppercase.png'),
    name: 'inputlatinuppercase',
  },
  {source: require('@assets/images/mem-images/pencil.png'), name: 'pencil'},
  {source: require('@assets/images/mem-images/hot.png'), name: 'hot'},
  {source: require('@assets/images/mem-images/racecar.png'), name: 'racecar'},
  {source: require('@assets/images/mem-images/bicycle.png'), name: 'bicycle'},
  {source: require('@assets/images/mem-images/compass.png'), name: 'compass'},
  {source: require('@assets/images/mem-images/bat.png'), name: 'bat'},
  {source: require('@assets/images/mem-images/log.png'), name: 'log'},
  {
    source: require('@assets/images/mem-images/sunglasses.png'),
    name: 'sunglasses',
  },
  {source: require('@assets/images/mem-images/tuxedo.png'), name: 'tuxedo'},
  {source: require('@assets/images/mem-images/banjo.png'), name: 'banjo'},
  {
    source: require('@assets/images/mem-images/bellslash.png'),
    name: 'bellslash',
  },
  {
    source: require('@assets/images/mem-images/skateboard.png'),
    name: 'skateboard',
  },
  {source: require('@assets/images/mem-images/soap.png'), name: 'soap'},
  {source: require('@assets/images/mem-images/giraffe.png'), name: 'giraffe'},
  {source: require('@assets/images/mem-images/usflag.png'), name: 'usflag'},
  {source: require('@assets/images/mem-images/hammer.png'), name: 'hammer'},
  {source: require('@assets/images/mem-images/crutch.png'), name: 'crutch'},
  {source: require('@assets/images/mem-images/anchor.png'), name: 'anchor'},
  {source: require('@assets/images/mem-images/page.png'), name: 'page'},
  {source: require('@assets/images/mem-images/bone.png'), name: 'bone'},
  {source: require('@assets/images/mem-images/star.png'), name: 'star'},
  {source: require('@assets/images/mem-images/guitar.png'), name: 'guitar'},
  {source: require('@assets/images/mem-images/boot.png'), name: 'boot'},
  {
    source: require('@assets/images/mem-images/construction.png'),
    name: 'construction',
  },
  {
    source: require('@assets/images/mem-images/cowboyface.png'),
    name: 'cowboyface',
  },
  {
    source: require('@assets/images/mem-images/telephone.png'),
    name: 'telephone',
  },
  {source: require('@assets/images/mem-images/fox.png'), name: 'fox'},
  {source: require('@assets/images/mem-images/sun.png'), name: 'sun'},
  {source: require('@assets/images/mem-images/wrench.png'), name: 'wrench'},
  {
    source: require('@assets/images/mem-images/shoppingbags.png'),
    name: 'shoppingbags',
  },
  {source: require('@assets/images/mem-images/cd.png'), name: 'cd'},
  {
    source: require('@assets/images/mem-images/fishingrod.png'),
    name: 'fishingrod',
  },
  {source: require('@assets/images/mem-images/toilet.png'), name: 'toilet'},
  {source: require('@assets/images/mem-images/wedding.png'), name: 'wedding'},
  {source: require('@assets/images/mem-images/goggles.png'), name: 'goggles'},
  {source: require('@assets/images/mem-images/beetle.png'), name: 'beetle'},
  {source: require('@assets/images/mem-images/postbox.png'), name: 'postbox'},
  {source: require('@assets/images/mem-images/bucket.png'), name: 'bucket'},
  {source: require('@assets/images/mem-images/bacteria.png'), name: 'bacteria'},
  {source: require('@assets/images/mem-images/bus.png'), name: 'bus'},
  {
    source: require('@assets/images/mem-images/beachumbrella.png'),
    name: 'beachumbrella',
  },
  {
    source: require('@assets/images/mem-images/carpentrysaw.png'),
    name: 'carpentrysaw',
  },
  {source: require('@assets/images/mem-images/darkear.png'), name: 'darkear'},
  {source: require('@assets/images/mem-images/openbook.png'), name: 'openbook'},
  {
    source: require('@assets/images/mem-images/christmastree.png'),
    name: 'christmastree',
  },
  {source: require('@assets/images/mem-images/club.png'), name: 'club'},
  {source: require('@assets/images/mem-images/otter.png'), name: 'otter'},
  {source: require('@assets/images/mem-images/dress.png'), name: 'dress'},
  {source: require('@assets/images/mem-images/swimsuit.png'), name: 'swimsuit'},
  {source: require('@assets/images/mem-images/camera.png'), name: 'camera'},
  {source: require('@assets/images/mem-images/printer.png'), name: 'printer'},
  {source: require('@assets/images/mem-images/oldwoman.png'), name: 'oldwoman'},
  {source: require('@assets/images/mem-images/unlocked.png'), name: 'unlocked'},
  {source: require('@assets/images/mem-images/coin.png'), name: 'coin'},
  {source: require('@assets/images/mem-images/pig.png'), name: 'pig'},
  {source: require('@assets/images/mem-images/slide.png'), name: 'slide'},
  {source: require('@assets/images/mem-images/purse.png'), name: 'purse'},
  {
    source: require('@assets/images/mem-images/exclamationmark.png'),
    name: 'exclamationmark',
  },
  {source: require('@assets/images/mem-images/tophat.png'), name: 'tophat'},
  {
    source: require('@assets/images/mem-images/polarbear.png'),
    name: 'polarbear',
  },
  {source: require('@assets/images/mem-images/scooter.png'), name: 'scooter'},
  {source: require('@assets/images/mem-images/trumpet.png'), name: 'trumpet'},
  {source: require('@assets/images/mem-images/saturn.png'), name: 'saturn'},
  {source: require('@assets/images/mem-images/dart.png'), name: 'dart'},
  {
    source: require('@assets/images/mem-images/saxophone.png'),
    name: 'saxophone',
  },
  {
    source: require('@assets/images/mem-images/yellowflower.png'),
    name: 'yellowflower',
  },
  {source: require('@assets/images/mem-images/pumpkin.png'), name: 'pumpkin'},
  {source: require('@assets/images/mem-images/broom.png'), name: 'broom'},
  {
    source: require('@assets/images/mem-images/partyface.png'),
    name: 'partyface',
  },
  {
    source: require('@assets/images/mem-images/stethoscope.png'),
    name: 'stethoscope',
  },
  {source: require('@assets/images/mem-images/kimono.png'), name: 'kimono'},
  {source: require('@assets/images/mem-images/crown.png'), name: 'crown'},
  {source: require('@assets/images/mem-images/peace.png'), name: 'peace'},
  {source: require('@assets/images/mem-images/police.png'), name: 'police'},
  {
    source: require('@assets/images/mem-images/paperclip.png'),
    name: 'paperclip',
  },
  {source: require('@assets/images/mem-images/theater.png'), name: 'theater'},
  {source: require('@assets/images/mem-images/yarn.png'), name: 'yarn'},
  {
    source: require('@assets/images/mem-images/firecracker.png'),
    name: 'firecracker',
  },
  {source: require('@assets/images/mem-images/gloves.png'), name: 'gloves'},
  {source: require('@assets/images/mem-images/bald.png'), name: 'bald'},
  {source: require('@assets/images/mem-images/syringe.png'), name: 'syringe'},
  {source: require('@assets/images/mem-images/motorway.png'), name: 'motorway'},
  {source: require('@assets/images/mem-images/xray.png'), name: 'xray'},
  {source: require('@assets/images/mem-images/horn.png'), name: 'horn'},
  {source: require('@assets/images/mem-images/pager.png'), name: 'pager'},
  {source: require('@assets/images/mem-images/tshirt.png'), name: 'tshirt'},
  {source: require('@assets/images/mem-images/razor.png'), name: 'razor'},
  {source: require('@assets/images/mem-images/siren.png'), name: 'siren'},
  {source: require('@assets/images/mem-images/snake.png'), name: 'snake'},
  {source: require('@assets/images/mem-images/bear.png'), name: 'bear'},
  {source: require('@assets/images/mem-images/kite.png'), name: 'kite'},
  {
    source: require('@assets/images/mem-images/keyboardcomputer.png'),
    name: 'keyboardcomputer',
  },
  {source: require('@assets/images/mem-images/magic8.png'), name: 'magic8'},
  {source: require('@assets/images/mem-images/chick.png'), name: 'chick'},
  {source: require('@assets/images/mem-images/redheart.png'), name: 'redheart'},
  {
    source: require('@assets/images/mem-images/lightbulb.png'),
    name: 'lightbulb',
  },
  {
    source: require('@assets/images/mem-images/horseracer.png'),
    name: 'horseracer',
  },
  {
    source: require('@assets/images/mem-images/divingmask.png'),
    name: 'divingmask',
  },
  {source: require('@assets/images/mem-images/scorpion.png'), name: 'scorpion'},
  {
    source: require('@assets/images/mem-images/lotionbottle.png'),
    name: 'lotionbottle',
  },
  {source: require('@assets/images/mem-images/firework.png'), name: 'firework'},
  {source: require('@assets/images/mem-images/skunk.png'), name: 'skunk'},
  {source: require('@assets/images/mem-images/tram.png'), name: 'tram'},
  {source: require('@assets/images/mem-images/snail.png'), name: 'snail'},
  {source: require('@assets/images/mem-images/brick.png'), name: 'brick'},
  {
    source: require('@assets/images/mem-images/conveniencestore.png'),
    name: 'conveniencestore',
  },
  {source: require('@assets/images/mem-images/ledger.png'), name: 'ledger'},
  {source: require('@assets/images/mem-images/teddy.png'), name: 'teddy'},
  {
    source: require('@assets/images/mem-images/clownface.png'),
    name: 'clownface',
  },
  {
    source: require('@assets/images/mem-images/crocodile.png'),
    name: 'crocodile',
  },
  {source: require('@assets/images/mem-images/fencing.png'), name: 'fencing'},
  {
    source: require('@assets/images/mem-images/ferriswheel.png'),
    name: 'ferriswheel',
  },
  {source: require('@assets/images/mem-images/bamboo.png'), name: 'bamboo'},
  {source: require('@assets/images/mem-images/rainbow.png'), name: 'rainbow'},
  {source: require('@assets/images/mem-images/vampire.png'), name: 'vampire'},
];
