export const SET_PROFILE = 'profile/SET_PROFILE'
export const SET_PROFILE_SUCCESS = 'profile/SET_PROFILE_SUCCESS'
export const SET_PROFILE_ERROR = 'profile/SET_PROFILE_ERROR'
export const SET_PROFILE_SUCCESS_FINISH = 'profile/SET_PROFILE_SUCCESS_FINISH'

export const GET_PROFILE = 'profile/GET_PROFILE'
export const GET_PROFILE_SUCCESS = 'profile/GET_PROFILE_SUCCESS'
export const GET_PROFILE_ERROR = 'profile/GET_PROFILE_ERROR'

export const REFRESH_TOKEN = 'profile/REFRESH_TOKEN'
export const REFRESH_TOKEN_SUCCESS = 'profile/REFRESH_TOKEN_SUCCESS'
export const REFRESH_TOKEN_ERROR = 'profile/REFRESH_TOKEN_ERROR'

export const GET_DB_PROFILE = 'profile/GET_DB_PROFILE'
export const GET_DB_PROFILE_SUCCESS = 'profile/GET_DB_PROFILE_SUCCESS'
export const GET_DB_PROFILE_ERROR = 'profile/GET_DB_PROFILE_ERROR'
export const RESET_PROFILE = 'profile/RESET_PROFILE'
export const SET_PROFILE_PHOTO = 'profile/SET_PROFILE_PHOTO'
export const SET_APNS_TOKEN = 'profile/SET_APNS_TOKEN'
export const SET_RREGISTRATION_TOKEN = 'profile/SET_RREGISTRATION_TOKEN'
export const CLEAR_ERRORS = 'auth/CLEAR_ERRORS'